export const DEFAULT_IDEAS = [
  { id: 1, title: "AI Study Buddy", category: "EdTech", icon: "🤖", likes: 124, desc: "An AI-powered personal study assistant that helps students learn faster with custom notes, quizzes and doubt solving.", problem: "Students struggle with managing study materials and getting instant help.", solution: "A personalized AI assistant for notes, quizzes and 24/7 doubt solving.", features: ["AI based Q&A", "Personalized study plans", "Progress tracking", "Multi-subject support"] },
  { id: 2, title: "EcoSwap", category: "Green Tech", icon: "🌱", likes: 98, desc: "A platform to buy, sell and swap used items locally.", problem: "Useful products are often discarded while others search for affordable alternatives.", solution: "A trusted local marketplace for exchanging reusable products.", features: ["Local discovery", "Simple listings", "Eco impact tracking", "Secure profiles"] },
  { id: 3, title: "MediTrack", category: "HealthTech", icon: "❤️", likes: 76, desc: "Track health data and get personalized insights.", problem: "People have health information spread across multiple apps and devices.", solution: "One simple dashboard for tracking habits and personal health metrics.", features: ["Health dashboard", "Reminders", "Trend insights", "Data export"] },
  { id: 4, title: "SkillShare", category: "EdTech", icon: "⭐", likes: 64, desc: "Learn and teach skills with a global community.", problem: "Learners struggle to find practical peer-to-peer learning.", solution: "A community marketplace connecting people who want to learn and teach.", features: ["Skill profiles", "Peer sessions", "Ratings", "Learning paths"] },
  { id: 5, title: "FarmConnect", category: "AgriTech", icon: "🌾", likes: 59, desc: "Connect farmers directly with buyers.", problem: "Farmers may lose margin through long distribution chains.", solution: "A direct discovery and communication platform for producers and buyers.", features: ["Direct discovery", "Price visibility", "Buyer profiles", "Order requests"] },
  { id: 6, title: "QuickCart", category: "E-commerce", icon: "🛒", likes: 51, desc: "A hyperlocal delivery platform for daily needs.", problem: "Customers want convenient access to nearby essentials.", solution: "Fast local shopping with neighborhood stores and delivery partners.", features: ["Nearby stores", "Quick ordering", "Order tracking", "Digital receipts"] },
  { id: 7, title: "FinPilot", category: "FinTech", icon: "💳", likes: 88, desc: "A personal finance planning companion for young professionals.", problem: "Budgeting can feel complex and inconsistent.", solution: "A simple planning workspace for goals, budgets and spending insights.", features: ["Goal planning", "Budget tools", "Spending insights", "Reminders"] },
  { id: 8, title: "CodeGuard", category: "AI & ML", icon: "🛡️", likes: 91, desc: "An educational code quality assistant for developers.", problem: "Beginners need understandable feedback when learning to code.", solution: "Clear explanations of common code-quality issues and improvements.", features: ["Code hints", "Readable feedback", "Learning tips", "Project checks"] },
];

export const CATEGORY_SUGGESTIONS = ["AI & ML", "EdTech", "FinTech", "HealthTech", "Green Tech", "E-commerce", "AgriTech", "Other"];
export const ICON_CHOICES = ["💡", "🤖", "🌱", "❤️", "⭐", "🌾", "🛒", "💳", "🛡️", "🚀", "📱", "🎓"];
